// <auto-generated />
using System;
using Hichain.Entity.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hichain.Entity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hichain.Entity.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "电子产品",
                            CreatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(2483),
                            Description = "高性能办公笔记本",
                            IsDeleted = false,
                            Name = "笔记本电脑",
                            Price = 5999.00m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(2484)
                        },
                        new
                        {
                            Id = 2,
                            Category = "电子产品",
                            CreatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(2492),
                            Description = "人体工学设计",
                            IsDeleted = false,
                            Name = "无线鼠标",
                            Price = 99.00m,
                            Stock = 500,
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(2493)
                        });
                });

            modelBuilder.Entity("Hichain.Entity.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            CreatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(1704),
                            Email = "admin@example.com",
                            IsDeleted = false,
                            Name = "管理员",
                            Password = "admin123",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(1706),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            Age = 25,
                            CreatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(1716),
                            Email = "user@example.com",
                            IsDeleted = false,
                            Name = "普通用户",
                            Password = "user123",
                            Role = "User",
                            UpdatedAt = new DateTime(2026, 4, 1, 14, 11, 39, 992, DateTimeKind.Utc).AddTicks(1718),
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
